# Generated by Django 5.0.1 on 2024-01-03 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_person', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('files', models.FileField(blank=True, null=True, upload_to='task_files/')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_state', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('weight', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task_mngr_app.task')),
            ],
        ),
    ]
