# Generated by Django 5.0.1 on 2024-01-03 21:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_mngr_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='task',
        ),
        migrations.RemoveField(
            model_name='state',
            name='task_state',
        ),
        migrations.AddField(
            model_name='state',
            name='title',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_mngr_app.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='working_person',
            field=models.CharField(max_length=30),
        ),
    ]
